### ISSUE TITLE
Request: Make nsqd sidecar pattern optional

### ISSUE THREAD

**Issue by Ashtonian** [BeeInventor/charts#1]
It would be nice if the chart was less opinionated and allowed the user to decide if they need to implement a sidecar pattern - maybe have it defaulted to the current behavior but allow enabling a couple of nsqd instances. The pattern is overkill in some prod environments and ci/cd pipelines and its unfortunate that this helm chart is not a complete deployment.

**Comment by benjamin658** [comment]
Hi @Ashtonian, thanks for your feedback.

I agree with your perspective "The pattern is overkill in some prod environments and ci/cd pipelines" , I will add the nsqd Deployment and allow the user to decide whether to deploy it or not.

I need to arrange a free time to do that, so it could be done in the next few weeks, however, the PR is still welcome :)

**Comment by Ashtonian** [comment]
PR submitted, just a heads up k8 is pretty new to me. Let me know if I need to change anything.

**Comment by benjamin658** [comment]
Thanks for your contribution, we will test it well.

**Comment by LordNoteworthy** [comment]
I come here for the same issue :) Thanks @Ashtonian for raising this. I have many services that produce to NSQ and was a bit an overkill to include NSQD in every deployment that I have,  I also had to change all the deployments to statefulsets ^^

**Comment by benjamin658** [comment]
@LordNoteworthy , thanks for your feedback.

The related PR is reviewing.
