### ISSUE TITLE
bump the app version to the newly released nsq

### ISSUE THREAD

**Issue by LordNoteworthy** [BeeInventor/charts#14]
Hi,

NSQ released a new version !  v.1.2.1.

We have a field normally to use a recent version of nsq but I was wondering if it would be good to bump the chart app version by default to this new release.

Cheers.

**Comment by benjamin658** [comment]
Sure, let me bump the nsq version!

Thanks for your reminder.

**Comment by benjamin658** [comment]
Hi @LordNoteworthy , I just bump the nsq version to 1.2.1 in 1f71640074d080bcfddb41e888ae928c863e8de7

Please upgrade to 1.2.0 chart version.
