### ISSUE TITLE
nsq: Support nsqlookupd service IP/port setting

### ISSUE THREAD

**Issue by mritd** [BeeInventor/charts#20]
I am a newbie to NSQ. Our application currently needs to find the topic producer (nsq) through the nsqlookupd http port(4161); 

I found that the nsqlookupd service address cannot be set in helm. Is this intentional or should I add this configuration?

**Comment by benjamin658** [comment]
You don't have to configure the address.

https://github.com/BeeInventor/charts/blob/aced84652920814ae6002da5bab36dd86d618e37/beeinventor/nsq/templates/nsqd-statefulset.yaml#L42-L46

**Comment by mritd** [comment]
I think I don't seem to express clearly; in the heml configuration I see that nsqd connects to nsqlookupd through template parameters; but my java application also needs to connect to nsqlookupd;

In the `k8s service` configuration of nsqlookup generated by Helm, the `k8s service` does not expose the ClusterIP, and my java application does not know how to connect to nsqlookupd.

**Comment by benjamin658** [comment]
The `nsqlookupd`  is deployed as a `StatefulSet`, you have to connect to every nsqlookupd pod to get the full topology information of nsqd.

For example, if you deploy the chart with nsqlookupd.replicaCount=3, the DNS could be 
```
${.Release.Name}-nsqlookupd-0.${.Release.Name}-nsqlookupd:4161
${.Release.Name}-nsqlookupd-1.${.Release.Name}-nsqlookupd:4161
${.Release.Name}-nsqlookupd-2.${.Release.Name}-nsqlookupd:4161
```

**Comment by mritd** [comment]
Thanks for your reply, I am currently using this way;
Off topic: Can I load balance nsqlookupd with k8s service?

**Comment by benjamin658** [comment]
> Thanks for your reply, I am currently using this way; Off topic: Can I load balance nsqlookupd with k8s service?

No, you shouldn't do that, just like I said, you have to connect to every nsqlookupd pod to get the full topology information of nsqd.

**Comment by mritd** [comment]
ok thanks
