### ISSUE TITLE
[nsq] DaemonSet support

### ISSUE THREAD

**Issue by acjohnson** [BeeInventor/charts#25]
We've been using a fork of your `nsq` chart for sometime now that makes use of static hostPorts for tcp and http container ports as well as disables storage persistence as `DaemonSet` does not support persistentVolumes/volumeClaimTemplates.

Would you be interested in a PR that would add the ability to enable `DaemonSet` support of course keeping the default functionality of using a `StatefulSet` intact?

I suspect it is possible to make `StatefulSet` run in a similar way, dedicated one pod per node by making use of anti-affinity and nodeSelectors, but using a `DaemonSet` instead seems to be a decent alternative in our environment and can share if you are interested.

**Comment by benjamin658** [comment]
Hi, Could you explain in more detail of practical use case that runs the nsq as a `DaemonSet `?

IMHO, storage persistence is mandatory for a message queue system.

**Comment by acjohnson** [comment]
The purpose of the `DaemonSet` is to ensure all nodes in a given node pool are always running an `nsqd` pod. Just like any of the `DaemonSet` that run inside the `kube-system` namespace or for other services such as log aggregation (loki/splunk/humio) or node metrics (prom node-exporter).

I wouldn't say storage persistence is mandatory if you are fine with using non-durable queues, which we have been for many months now in our use case.

**Comment by benjamin658** [comment]
PodAntiAffinity seems like an easy way to achieve it, so recommending a DaemonSet alternative seems overly aggressive. Thanks for your recommendation, btw.
