### ISSUE TITLE
deprecated Ingress object for apiVersion=extensions/v1beta1

### ISSUE THREAD

**Issue by lucianmoise** [BeeInventor/charts#3]
Hello,

**es-client-ingress.yaml**  and **kibana-ingress.yml** use a deprecated _apiVersion=extensions/v1beta1_   for Ingress object.
According to [https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122) , Ingress will no longer be served in v1.22 of k8s .

Regards

**Comment by benjamin658** [comment]
Fixed in #17 .

**Comment by benjamin658** [comment]
Use this PR version instead #18
