### ISSUE TITLE
nsqd docs and additional config

### ISSUE THREAD

**Issue by Ashtonian** [BeeInventor/charts#6]
just starting convo here, will submit pr. Need to add docs for nsqd to readme. 

Additionally would like to add a couple of missing things to values.yaml for all nsq services: 

* priorityClassName: 
* extraArgs[]
* terminationMessagePolicy: FallbackToLogsOnError

**Comment by benjamin658** [comment]
Sure, thanks for your contribution!

**Comment by Ashtonian** [comment]
also adding       `serviceAccountName: `
